### PR TITLE
script for fixing bind mount

### PR DESCRIPTION
**Pull request by frankfont**
With this script, I am able to run stacks that use the file bind feature of docker-compose.

### CODE REVIEW

**Comment by cjdesautels** [comment]
So this should have no impact on the rest of zcmd. It's purpose is to support binds? What needs to be fixed? We've been using binds all along.

**Comment by cjdesautels** [comment]
And if it's beta, why are we merging to master?
I hope all is well with you. Give me a call and we'll yak.

**Comment by frankfont** [comment]
Hi Chris,

Yeah it's an isolated script. No impact unless someone knows to call it.
Only purpose is to make binds usable for folks using windows 10... Binds
dont work on that os unless do something like this.

Beta/experimental because I've only run one test and will try to refine in
future.

Sincerely
Frank

**Comment by cjdesautels** [comment]
Cool, I remember you mentioned this bleeding edge fix for Docker/Windows. So if you pull it off, our stacks will run fine on a windows machine?

**Comment by cjdesautels** [comment]
I've merged it into master

**Comment by cjdesautels** [comment]
Keep me posted on it's progress.

**Comment by frankfont** [comment]
Cool.  Yes should work already for anyone running the WSL option on Windows
10.

**Pull request merged**
