### PR TITLE
Frank stage

### PR DESCRIPTION
**Pull request by frankfont**
Enhanced the machine.env to allow arbitrary port number mappings via the MACHINE_PORT80=1234 convention.  For example, if you want to map port 4200 to 8080 on the host simply add this environment variable into your machine.env file ...

MACHINE_PORT4200=8080

### CODE REVIEW

**Comment by cjdesautels** [comment]
By machine.env, you mean stack.env? How is this a change from what's been in place on those files for some time now?

**Comment by frankfont** [comment]
Machine.env is for building machines.  This enhancement only for running
dockerfile builds in machine folder.

Stack.env is what we use for stack folders.

**Comment by cjdesautels** [comment]
So what would be the use case where you would want to map ports in the image and not leave it to the docker-compose.yml?

**Comment by frankfont** [comment]
Building and testing containers.  The zcmd run in those folders uses the
machine.env entries to provide a usable instance.

The original implementation onlyn supports a few specific ports.  Now all
are supported.  I ran into this building node and angular containers a few
weeks ago so made the enhancement.

**Comment by cjdesautels** [comment]
Ok, so you are using zcmd in your new job. Cool. So I'm unclear what's next. You've submitted a "preview request" and I have an option to perform a "Merge pull request". I assume that this is the typical workflow on Github? Rather then what I did a few weeks ago, merge into master on my local and slapped it up on Github without so much as a howdy-doo to my co-maintainer.

**Comment by frankfont** [comment]
Next step?  If you are ok with the update use the merge button on github.
Benefit of this over local merge push is the message workflow/transparency
of coordination.

**Comment by frankfont** [comment]
@cjdesautels  I also improved the "--help" feature of zcmd core script.  Tested on a Mac today.  I don't see any problems.  How about you merge it with master or give me a thumbs up and I will do it.

**Comment by cjdesautels** [comment]
I merged into frank-stage into master and deleted frank-stage.

**Pull request merged**
